package com.jackie.myapp.model;

import java.util.Date;

public class Fileinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.id
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.filename
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.filepath
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private String filepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.description
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.anthor
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private String anthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.is_delete
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.upload_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.update_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.create_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.id
     *
     * @return the value of fileinfo.id
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.id
     *
     * @param id the value for fileinfo.id
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.filename
     *
     * @return the value of fileinfo.filename
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.filename
     *
     * @param filename the value for fileinfo.filename
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.filepath
     *
     * @return the value of fileinfo.filepath
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.filepath
     *
     * @param filepath the value for fileinfo.filepath
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.description
     *
     * @return the value of fileinfo.description
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.description
     *
     * @param description the value for fileinfo.description
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.anthor
     *
     * @return the value of fileinfo.anthor
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public String getAnthor() {
        return anthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.anthor
     *
     * @param anthor the value for fileinfo.anthor
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setAnthor(String anthor) {
        this.anthor = anthor == null ? null : anthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.is_delete
     *
     * @return the value of fileinfo.is_delete
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.is_delete
     *
     * @param isDelete the value for fileinfo.is_delete
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.upload_time
     *
     * @return the value of fileinfo.upload_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.upload_time
     *
     * @param uploadTime the value for fileinfo.upload_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.update_time
     *
     * @return the value of fileinfo.update_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.update_time
     *
     * @param updateTime the value for fileinfo.update_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.create_time
     *
     * @return the value of fileinfo.create_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.create_time
     *
     * @param createTime the value for fileinfo.create_time
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}