package com.jackie.myapp.mapper;

import com.jackie.myapp.model.Fileinfo;

public interface FileinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    int insert(Fileinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    int insertSelective(Fileinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    Fileinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    int updateByPrimaryKeySelective(Fileinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbg.generated Mon May 27 12:23:33 CST 2019
     */
    int updateByPrimaryKey(Fileinfo record);
}